export const GET_TRIPS = 'GET_TRIPS';
export const GET_SINGLE_TRIP = 'GET_SINGLE_TRIP';
export const CLEAR_SINGLE_TRIP = 'CLEAR_SINGLE_TRIP';
export const GET_ALL_POST_NUBER = 'GET_ALL_POST_NUMBER';
export const GET_ALL_PAGES_NUMBER = 'GET_ALL_PAGES_NUMBER';
export const CLEAR_ALL_TRIPS = 'CLEAR_ALL_TRIPS';
