export const GET_TRIPS = 'GET_TRIPS';
export const GET_SINGLE_TRIP = 'GET_SINGLE_TRIP';
export const CLEAR_SINGLE_TRIP = 'CLEAR_SINGLE_TRIP';
export const GET_ALL_POST_NUMBER = 'GET_ALL_POST_NUMBER';
export const GET_ALL_POST_PAGES = 'GET_ALL_POST_PAGES';
export const CLEAR_ALL_TRIPS = 'CLEAR_ALL_TRIPS';
export const GET_SIDEBAR_POSTS = 'GET_SIDEBAR_POSTS';
export const UPDATE_PAGE_NR_POSTS = 'UPDATE_PAGE_NR_POSTS';

export const GET_NEWS = 'GET_NEWS';
export const GET_SINGLE_NEWS = 'GET_SINGLE_NEWS';
export const CLEAR_SINGLE_NEWS = 'CLEAR_SINGLE_NEWS';
export const GET_ALL_NEWS_NUMBER = 'GET_ALL_NEWS_NUMBER';
export const GET_ALL_NEWS_PAGES = 'GET_ALL_NEWS_PAGES';
export const CLEAR_ALL_NEWS = 'CLEAR_ALL_NEWS';
export const GET_SIDEBAR_NEWS = 'GET_SIDEBAR_NEWS';
